public class Main {
    public static void main(String[] args) {
        System.out.println("задача № 1");
        var dog = 8.0;
        System.out.println(dog);
        var cat = 3.6;
        System.out.println(cat);
        var paper = 763789;
        System.out.println(paper);
        System.out.println("задача № 2");
        var dog1 = 8.0;
        System.out.println(dog1);
        dog1 = dog1 + 4;
        System.out.println(dog1);
        var cat1 = 3.6;
        System.out.println(cat1);
        cat1 = cat1 + 4;
        System.out.println(cat1);
        var paper1 = 763789;
        System.out.println(paper1);
        paper1 = paper1 + 4;
        System.out.println(paper1);
        System.out.println("задача № 3");
        var dog2 = 8.0;
        System.out.println(dog2);
        dog2 = dog2 + 4;
        System.out.println(dog2);
        dog2 = dog2 - 3.5;
        System.out.println(dog2);
        var cat2 = 3.6;
        System.out.println(cat2);
        cat2 = cat2 + 4;
        System.out.println(cat2);
        cat2 = cat2 - 1.6;
        System.out.println(cat2);
        var paper2 = 763789;
        System.out.println(paper2);
        paper2 = paper2 + 4;
        System.out.println(paper2);
        paper2 = paper2 - 7639;
        System.out.println(paper2);
        System.out.println("задача № 4");
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        System.out.println("задача № 5");
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog +4;
        System.out.println(frog);
        System.out.println("задача № 6");
        var firstBoxerWeight = 78.2;
        var secondBoxerWeight = 82.7;
        System.out.println(firstBoxerWeight + secondBoxerWeight);
        System.out.println(secondBoxerWeight - firstBoxerWeight);
        System.out.println("задача № 7");
        var firstBoxerWeight1 = 78.2;
        var secondBoxerWeight1 = 82.7;
        System.out.println(firstBoxerWeight1 + secondBoxerWeight1);
        System.out.println(secondBoxerWeight1 - firstBoxerWeight1);
        System.out.println(secondBoxerWeight1 % firstBoxerWeight1);
        System.out.println("задача № 8");
        var watch = 640;
        watch = watch / 8;
        System.out.println("Всего работников в компании " + watch);
        var staff = 80;
        staff = staff + 94;
        System.out.println(staff);
        watch = watch * 8;
        System.out.println(watch /staff );
        System.out.println("Если в компании работает 174 человек " + "то всего 3 часа работы может быть поделено между сотрудниками");

    }
}
